services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
    volumes:
      - pgdata:/bitnami/postgresql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pgdata: